name: "CI"
on: 
  push:
    branches:
      - main
      - bug/conferencia-veiculos

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        npm ci
        npm run all
  test: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 8
    - name: Use coturiv/setup-ionic
      uses: ./
    - name: Run cordova project tests
      run: |
        ionic start testapp blank --cordova --type angular --no-link --no-git --no-interactive --confirm
        cd testapp
        ionic cordova platform add android@latest
        ionic cordova build android
